// 50 usuarios con roles variados [nombre, email, avatar, tipo]
const USUARIOS = [
  // Administradores (3)
  ['María Gómez','maria@ejemplo.com','👩','admin'],
  ['Roberto Sánchez','roberto.sanchez@mundial2026.com','👨','admin'],
  ['Laura Mendoza','laura.mendoza@mundial2026.com','👩','admin'],
  // Operadores (7)
  ['Carlos López','carlos.lopez@email.com','👨','operador'],
  ['Andrea Ramírez','andrea.ramirez@email.com','👩','operador'],
  ['Felipe Morales','felipe.morales@email.com','👨','operador'],
  ['Daniela Castro','daniela.castro@email.com','👩','operador'],
  ['Operador Sistema','operador@mundial2026.com','🔧','operador'],
  ['Sergio Vargas','sergio.vargas@email.com','👨','operador'],
  ['Paula Navarro','paula.navarro@email.com','👩','operador'],
  // Aficionados (40)
  ['Ana Martínez','ana.martinez@email.com','👩','aficionado'],
  ['Juan Pérez','juan.perez@email.com','👨','aficionado'],
  ['Sofía Rodríguez','sofia.rdz@email.com','👧','aficionado'],
  ['Diego Hernández','diego.h@email.com','🧑','aficionado'],
  ['Valentina Torres','vale.torres@email.com','👩','aficionado'],
  ['Andrés Mora','andres.mora@email.com','👨','aficionado'],
  ['Camila Ruiz','camila.r@email.com','👧','aficionado'],
  ['Santiago Díaz','santi.diaz@email.com','👦','aficionado'],
  ['Isabella García','isa.garcia@email.com','👩','aficionado'],
  ['Mateo Ospina','mateo.ospina@email.com','👨','aficionado'],
  ['Luciana Reyes','luci.reyes@email.com','👩','aficionado'],
  ['Tomás Herrera','tomas.h@email.com','🧑','aficionado'],
  ['Mariana Jiménez','mariana.j@email.com','👧','aficionado'],
  ['Nicolás Arias','nico.arias@email.com','👨','aficionado'],
  ['Gabriela Pinto','gabi.pinto@email.com','👩','aficionado'],
  ['Alejandro Muñoz','alejo.munoz@email.com','👨','aficionado'],
  ['Fernanda Cárdenas','fer.cardenas@email.com','👧','aficionado'],
  ['Julián Rojas','julian.rojas@email.com','🧑','aficionado'],
  ['Carolina Duarte','caro.duarte@email.com','👩','aficionado'],
  ['Sebastián Leal','seba.leal@email.com','👨','aficionado'],
  ['Paola Suárez','paola.suarez@email.com','👩','aficionado'],
  ['Emilio Cortés','emilio.cortes@email.com','👨','aficionado'],
  ['Catalina Vergara','cata.vergara@email.com','👧','aficionado'],
  ['Ricardo Peña','ricardo.pena@email.com','🧑','aficionado'],
  ['Natalia Salazar','nata.salazar@email.com','👩','aficionado'],
  ['Daniel Mejía','daniel.mejia@email.com','👨','aficionado'],
  ['Adriana Quintero','adri.quintero@email.com','👧','aficionado'],
  ['Esteban Cruz','esteban.cruz@email.com','👨','aficionado'],
  ['Mónica Aguilar','monica.aguilar@email.com','👩','aficionado'],
  ['Luis Fernández','luis.fernandez@email.com','🧑','aficionado'],
  ['Clara Rincón','clara.rincon@email.com','👧','aficionado'],
  ['Iván Bernal','ivan.bernal@email.com','👨','aficionado'],
  ['Teresa Camacho','teresa.camacho@email.com','👩','aficionado'],
  ['Óscar Gutiérrez','oscar.gutierrez@email.com','👨','aficionado'],
  ['Lorena Acosta','lorena.acosta@email.com','👧','aficionado'],
  ['Hugo Arévalo','hugo.arevalo@email.com','🧑','aficionado'],
  ['Viviana Ortega','viviana.ortega@email.com','👩','aficionado'],
  ['Rafael Montoya','rafael.montoya@email.com','👨','aficionado'],
  ['Esperanza Vega','esperanza.vega@email.com','👩','aficionado'],
  ['Miguel Bonilla','miguel.bonilla@email.com','👨','aficionado'],
];

module.exports = { USUARIOS };
